### PR TITLE
Added translation to Russian. intl_ru.arb

### PR DESCRIPTION
**Pull request by un-logic**
Initial translation to Russian. Locale ru_RU.

### CODE REVIEW

**Comment by un-logic** [comment]
Not sure about syntax for plural forms of numerals as Russian has four forms, please doublecheck lines
- 34
- 38
- 154

**Comment by mu-fazil-vk** [comment]
Okay, thanks for the PR. Can I add your profile to the Translators section in FluxTube?

**Comment by un-logic** [comment]
I have no strong feelings one way or the other. 
I meant to say 'it is only fair'.
Thank you!

**Comment by mu-fazil-vk** [comment]
Okay 👍

**Comment by un-logic** [comment]
@mu-fazil-vk just to give you a heads up, I've finalized translation on Crowdin. Replies counter was broken due to my inexperience with arb format, it must be fixed now.

**Pull request merged**
