### PR TITLE
Add TR Locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by mu-fazil-vk** [comment]
Thanks for the PR.

**Comment by mu-fazil-vk** [comment]
Can I add your profile to the Translators section in FluxTube?

**Comment by mikropsoft** [comment]
> Can I add your profile to the Translators section in FluxTube?

Of course it is possible, thank you.

**Comment by mu-fazil-vk** [comment]
Okay 👍

**Pull request merged**
